---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support, cloud manager 
summary: Astra Trident是由NetApp維護的完全支援開放原始碼專案。Astra Trident與Kubernetes及其持續Volume架構原生整合、可從執行任何NetApp儲存平台組合的系統無縫配置及管理Volume。 
---
= Kubernetes的資料管理功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident是由NetApp維護的完全支援開放原始碼專案。Astra Trident與Kubernetes及其持續Volume架構原生整合、可從執行任何NetApp儲存平台組合的系統無縫配置及管理Volume。 link:https://docs.netapp.com/us-en/trident/index.html["深入瞭解 Trident"^]。



== 功能

使用 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html["藍圖"^] （前身為 Cloud Manager ）、以及使用 Trident 運算子部署的相容版本 Astra Trident 、您可以：

* 新增及管理 Kubernetes 叢集
* link:./task/task-k8s-manage-trident.html["安裝、升級或解除安裝 Astra Trident"]
* link:./task/task-k8s-manage-storage-classes.html["新增及移除儲存類別"]
* link:./task/task-k8s-manage-persistent-volumes.html["檢視持續磁碟區"]
* link:./task/task-k8s-manage-remove-cluster.html["移除 Kubernetes 叢集"] 從工作區
* link:./task/task-kubernetes-enable-services.html["啟動或檢視 Cloud Backup"]




== 支援的Kubernetes部署

BlueXP支援在下列環境中執行的託管Kubernetes叢集：

* link:./requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes服務（Amazon EKS）"]
* link:./requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes服務（英文）"]
* link:./requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine（GKE）"]




== 支援的Astra Trident部署

Astra Trident的四個最新版本之一 link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["使用Trident運算子進行部署"^] 為必填項目。


NOTE: 使用部署Astra Trident `tridentctl` 不受支援。如果您使用部署Astra Trident `tridentctl`、您無法使用BlueXP來管理Kubernetes叢集。您必須  並重新安裝 link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["使用Trident運算子"^] 或 link:./tasks/task-k8s-manage-trident.html["使用BlueXP"]。

您可以直接從BlueXP安裝或升級至最新版的Astra Trident。

link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["檢閱Astra Trident的先決條件"^]



== 支援的後端儲存設備

NetApp Astra Trident必須安裝在每個Kubernetes叢集上、Cloud Volumes ONTAP 且必須ONTAP 將適用於此功能的EFlash或Amazon FSX設定為叢集的後端儲存設備。



== 成本

在BluesXP中、您的Kubernetes叢集不需付費、但當您使用Cloud Backup Service 更新功能來備份持續的磁碟區時、系統將會收取您的費用。
